version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: olayan
            POSTGRES_USER: olayan
            POSTGRES_PASSWORD: olayan
        volumes:
            - postgres-data:/var/lib/postgresql/data

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    springboot-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: springboot
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/olayan
            SPRING_DATASOURCE_USERNAME: olayan
            SPRING_DATASOURCE_PASSWORD: olayan
            SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/olayan
        depends_on:
            - postgres
            - mongo

volumes:
    postgres-data:
    mongo-data:
